
version: "3.8"
services:
  dashy:
    container_name: Dashy
    image: lissy93/dashy
    ports:
      - 4000:80
    networks:
      - proxy
    environment:
      - TZ=America/New_York
      - NODE_ENV=production
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.dashy.rule=Host(`dashy.your.domain.com`)'
      - "traefik.http.routers.dashy.service=dashy"
      - "traefik.http.services.dashy.loadBalancer.server.port=80"
      - "traefik.http.routers.dashy.tls=true"
      - "traefik.http.routers.dashy.tls.certresolver=cloudflare"
      - "traefik.http.routers.dashy.entrypoints=http"
      - "traefik.http.routers.dashy.middlewares=dashy-https-redirect,dashy-headers"
      # Add security headers similar to your guacamole setup
      - "traefik.http.middlewares.dashy-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.dashy-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.dashy-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.dashy-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.dashy-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.dashy-headers.headers.STSPreload=true"
      - "traefik.http.middlewares.dashy-https-redirect.redirectscheme.scheme=https"

networks:
  proxy:
    external: true
