version: '3.4'

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
      # If you have a custom config, uncomment and modify the lines below.
      #- ./config.custom.php:/var/www/FreshRSS/data/config.custom.php
      #- ./config-user.custom.php:/var/www/FreshRSS/data/config-user.custom.php
    ports:
      - "8081:80" # Changed to 8081 to avoid port conflicts. Adjust if needed.
    networks:
      - proxy
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.freshrss.rule=Host(`freshrss.your.domain.com`)'
      - "traefik.http.routers.freshrss.service=freshrss"
      - "traefik.http.services.freshrss.loadBalancer.server.port=80"
      - "traefik.http.routers.freshrss.tls=true"
      - "traefik.http.routers.freshrss.tls.certresolver=cloudflare"
      - "traefik.http.routers.freshrss.entrypoints=http"
      - "traefik.http.routers.freshrss.middlewares=freshrss-https-redirect,freshrss-headers"
      # Add security headers similar to your guacamole setup
      - "traefik.http.middlewares.freshrss-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.freshrss-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.freshrss-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.freshrss-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.freshrss-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.freshrss-headers.headers.STSPreload=true"
      - "traefik.http.middlewares.freshrss-https-redirect.redirectscheme.scheme=https"

volumes:
  freshrss-data:
  freshrss-extensions:

networks:
  proxy:
    external: true
