version: '3'
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.     #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
    ports:
      - 7575:7575
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.homarr.rule=Host(`homarr.your.domain.com`)'
      - "traefik.http.routers.homarr.service=homarr"
      - "traefik.http.services.homarr.loadBalancer.server.port=7575"
      - "traefik.http.routers.homarr.tls=true"
      - "traefik.http.routers.homarr.tls.certresolver=cloudflare"
      - "traefik.http.routers.homarr.entrypoints=http"
      - "traefik.http.routers.homarr.middlewares=homarr-https-redirect,homarr-headers"
      # Add security headers similar to your guacamole setup
      - "traefik.http.middlewares.homarr-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.homarr-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.homarr-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.homarr-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.homarr-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.homarr-headers.headers.STSPreload=true"
      - "traefik.http.middlewares.homarr-https-redirect.redirectscheme.scheme=https"
      
networks:
  proxy:
    external: true
