---
version: "2.1"
services:
  your_spotify:
    image: lscr.io/linuxserver/your_spotify:latest
    container_name: your_spotify
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - APP_URL=https://spotify.your.domain.com
      - SPOTIFY_PUBLIC=your_public_key
      - SPOTIFY_SECRET=your_secret_key
      - CORS=http://localhost:80
      - MONGO_ENDPOINT=mongodb://mongo:27017/your_spotify
    ports:
      - 8082:80
    networks:
      - proxy
      - spotify_network
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.spotify.rule=Host(`spotify.your.domain.com`)'
      - "traefik.http.routers.spotify.service=spotify"
      - "traefik.http.services.spotify.loadBalancer.server.port=80"
      - "traefik.http.routers.spotify.tls=true"
      - "traefik.http.routers.spotify.tls.certresolver=cloudflare"
      - "traefik.http.routers.spotify.entrypoints=http"
      - "traefik.http.routers.spotify.middlewares=spotify-https-redirect,spotify-headers"
      # Add security headers similar to your guacamole setup
      - "traefik.http.middlewares.spotify-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.spotify-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.spotify-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.spotify-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.spotify-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.spotify-headers.headers.STSPreload=true"
      - "traefik.http.middlewares.spotify-https-redirect.redirectscheme.scheme=https"

  mongo:
    image: mongo:4.4.8
    container_name: your_spotify-db
    restart: unless-stopped
    volumes:
      - ./mongo-data:/data/db
    networks:
      - spotify_network
      - proxy

networks:
  proxy:
    external: true
  spotify_network:
    external: false