---
version: "2.1"
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DB_TYPE=sqlite 
    volumes:
      - ./wikijs/configs:/app/data/configs
      - ./wikijs/data:/app/data/
    ports:
      - 3000:3000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.wikijs.rule=Host(`wikijs.your.domain.com`)'
      - "traefik.http.routers.wikijs.service=wikijs"
      - "traefik.http.services.wikijs.loadBalancer.server.port=3000"
      - "traefik.http.routers.wikijs.tls=true"
      - "traefik.http.routers.wikijs.tls.certresolver=cloudflare"
      - "traefik.http.routers.wikijs.entrypoints=http"
      - "traefik.http.routers.wikijs.middlewares=wikijs-https-redirect,wikijs-headers"
      # Add security headers similar to your guacamole setup
      - "traefik.http.middlewares.wikijs-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.wikijs-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.wikijs-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.wikijs-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.wikijs-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.wikijs-headers.headers.STSPreload=true"
      - "traefik.http.middlewares.wikijs-https-redirect.redirectscheme.scheme=https"

networks:
  proxy:
    external: true